
---
- name: Install Apache
  yum:
    name: httpd
    state: latest

- name: Start and enable Apache service
  systemd:
    name: httpd
    state: started
    enabled: yes

- name: Start and enable firewalld
  systemd:
    name: firewalld
    state: started
    enabled: yes

- name: Configure firewalld to allow HTTP
  firewalld:
    service: http
    permanent: yes
    state: enabled
    immediate: yes

- name: Deploy index.html template
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
